v 1

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -2,18 +2,48 @@ name: CD
 
 on:
   push:
-    branches: [ "test" ]
+    branches: [ "CD" ]
   pull_request:
 
 jobs:
+
+  install-docker:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Install Docker on VPS if missing
+        uses: appleboy/ssh-action@v1.2.0
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SERVER_SSH_KEY }}
+          script: |
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing Docker..."
+              sudo apt update
+              sudo apt install -y ca-certificates curl gnupg lsb-release
+              sudo install -m 0755 -d /etc/apt/keyrings
+              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
+              echo \
+                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+              sudo apt update
+              sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+              echo "Docker installed successfully."
+            else
+              echo "Docker already installed."
+            fi
+
   deploy:
     runs-on: ubuntu-latest
+    needs: install-docker
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Ensure directory exists
+      - name: dir & git & make
         uses: appleboy/ssh-action@v1.2.0
         with:
           host: ${{ secrets.SERVER_HOST }}
@@ -21,6 +51,8 @@ jobs:
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
             mkdir -p /home/site/backend
+            git config --global --add safe.directory /home/site/backend
+            sudo apt install make -y
 
       - name: Upload project to server
         uses: appleboy/scp-action@v0.1.4
